### ISSUE TITLE
reana.yaml: allow environments to be inputs as well

### ISSUE THREAD

**Issue by dprelipcean** [reanahub/reana#189]
# User desire
Rather than to have the environment hardcoded, such as:
i) for serial:
```
workflow:
  type: serial
  specification:
    steps:
      - environment: 'reanahub/reana-env-aliphysics:vAN-20180614-1'
```
ii) for cwl:
```
requirements:
  - class: DockerRequirement
    dockerPull: cmsopendata/cmssw_5_3_32
```

It would be useful to have it as an `input` that can be changed, e.g. in the `inputs` section/file, such that one only has to change `parameters` inside a single file and not in multiple files/parts of the code.

# Why such a feature?
When running the [CMS reconstruction](https://github.com/reanahub/reana-demo-cms-reco/issues/1), there are different images for different datasets, but the workflow is identical.
