### ISSUE TITLE
storage: initial EOS support

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#216]
Make EOS available in:
- REANA Kubernetes jobs
- REANA interactive sessions

**Comment by diegodelemos** [comment]
PR group working, tested on `reana-dev.cern.ch` with:

```yaml
version: 0.6.0
workflow:
  type: serial
  specification:
    steps:
      - name: testeos
        environment: 'reanahub/reana-demo-atlas-recast-eventselection'
        kerberos: true
        commands:
        - klist
        - cat /eos/user/r/rodrigdi/does-eos-work-with-reana.txt
        - echo "Yes it does :)" > /eos/user/r/rodrigdi/does-eos-work-with-reana.txt
        - cat /eos/user/r/rodrigdi/does-eos-work-with-reana.txt
```
And the output:
```console
$ reana-client run
$ reana-client logs -w workflow
JOB LOGS
job id: 85119571-e16a-43db-8516-103f79ae90f8
krb5: 
  
job: 
 Ticket cache: FILE:/krb5_cache/krb5_1000
Default principal: rodrigdi@CERN.CH

Valid starting     Expires            Service principal
12/06/19 16:54:01  12/07/19 17:54:01  krbtgt/CERN.CH@CERN.CH
        renew until 12/11/19 16:54:01
 

job id: 4d6e4c6d-1c91-4c1e-add1-b38d9cf1d57d
krb5: 
  
job: 
 I don't know :/
 

job id: adc4da93-cfd9-4b3b-a7ef-cc507e4ea64d
krb5: 
  
job: 
  

job id: ad0d487a-edd2-498c-a9ec-073561d50cc8
krb5: 
  
job: 
 Yes it does :)
```

Looks like the interactive sessions are currently broken there so no chance to try EOS on the Notebook session:

```console
$ reana-client open jupyter -w workflow  
Interactive session could not be opened: 
(500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Fri, 06 Dec 2019 15:55:31 GMT', 'Content-Length': '240'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"no kind \"Ingress\" is registered for version \"extensions/v1beta1\" in scheme \"k8s.io/apimachinery/pkg/apis/meta/internalversion/register.go:31\"","code":500}
```
