### ISSUE TITLE
docs: kerberos usage example doesn't work

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#218]
```yaml
workflow:
  type: serial
  resources:
    cvmfs:
      - fcc.cern.ch
  specification:
    steps:
      kerberos: true
      - environment: 'cern/slc6-base'
        commands:
        - ls -l /cvmfs/fcc.cern.ch/sw/views/releases/
```

https://reana.readthedocs.io/en/latest/userguide.html#declare-necessary-resources
