### ISSUE TITLE
How to add own gitlab on the user interface?

### ISSUE THREAD

**Issue by arm2arm** [reanahub/reana#648]
Hi,
following the steps in https://docs.reana.io/advanced-usage/code-repositories/gitlab/
![image](https://user-images.githubusercontent.com/2283443/174870342-3cfa01fb-03e8-4323-9efb-fa24ca41d0e1.png)

when I click on my local deployed instance it turns out 
![image](https://user-images.githubusercontent.com/2283443/174870164-db2513b1-ed6d-4d92-9eab-26ef0d4a53f7.png)
How to enable own custom gitlab instance in the reana gui?

**Comment by tiborsimko** [comment]
Hi @arm2arm, there is a `secrets.gitlab.REANA_GITLAB_HOST` helm value you can set during helm deployment, please see https://github.com/reanahub/reana/tree/0.8.1/helm/reana. Note also `REANA_GITLAB_OAUTH_APP_ID` and friends.

You can try something like:

```yaml
secrets:
  gitlab:
    REANA_GITLAB_HOST: gitlab.example.org
    REANA_GITLAB_OAUTH_APP_ID: 1111    
    REANA_GITLAB_OAUTH_APP_SECRET: 2222
```
