### ISSUE TITLE
How to deploy reana behind the haproxy or traefik2?

### ISSUE THREAD

**Issue by arm2arm** [reanahub/reana#655]
Hello,
We are accounting some connection problems with reana selfhosted server behind the haproxy. We would like to do ssl truncation for the internal network.
We have deployed reana following the documentation: https://docs.reana.io/administration/deployment/deploying-locally/
The final reana instance is listening to 30443 with SSL and local certificate. How we can deploy it to listen only on 80 port without SSL?

thank you beforehand.

**Comment by VMois** [comment]
In addition to port `30443`, REANA should listen on port `30080` without TLS. Will port `30080` work for you?

Sorry for the late reply.

**Comment by arm2arm** [comment]
Thank you! I will try this as soon as possible, need to fix some other issues, will give a feedback later.

**Comment by arm2arm** [comment]
I did those steps but the port 30080 gets redirected to 30443, do I miss some option for reana to disable redirection?

**Comment by arm2arm** [comment]
Ok I found the workaround:
* create a file myvalues.yaml
```
# Accessing the cluster from outside world
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.entryPoints: "http,https"
    ingress.kubernetes.io/ssl-redirect: "false"
  tls:
    self_signed_cert: true
```
* update
```
 helm  upgrade   -f myvalues.yaml reana reanahub/reana --namespace reana --create-namespace --wait
```
