### ISSUE TITLE
Idea: consider using GHA reusable workflows

### ISSUE THREAD

**Issue by Sinclert** [reanahub/reana#665]
👋🏻 Hi there

GitHub Actions introduced _reusable workflows_ at the end of last year (see their [blog post](https://github.blog/2021-11-29-github-actions-reusable-workflows-is-generally-available/)), and they are a nice way to standardise workflows across repositories, when they share similar steps. I thought this project may be a good candidate for their usage, given the **extremely similar** set of _steps_, on every `ci.yml` workflow, of every Python based repository.

Regular workflows can be marked as _reusable_ by adding the `workflow_call` keyword on their `on` trigger definition, and parametrised by adding the `inputs` and `secrets` keys within that trigger ([example here](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow)). Then, workflows can invoke them by using the `jobs.<job_name>.uses` syntax, specifying a path within GitHub.com.

As an example:

```yaml
name: CI

on: [push, pull_request]

jobs:
  continuous-integration:
    # Assumes a reusable workflow is defined within reanahub/github-workflows
    uses: reanahub/github-workflows/.github/workflows/ci.yml@main
    with:
      <input-1>: ...
      <input-2>: ...
```
