### ISSUE TITLE
Unable to configure the send mail functionality 

### ISSUE THREAD

**Issue by arm2arm** [reanahub/reana#670]
According to the documentation https://github.com/reanahub/reana/tree/master/helm/reana we have configured the **values.yaml** to enable email notifications and validations. Unfortuneatly our internal mailserver is not SSL encrypted. So in order to test the mail functions we moved to DEBUG mode according this line in the https://github.com/reanahub/reana-commons/blob/1b9aa72a7090870f60335e75e592e6f3737debc2/reana_commons/email.py#L48 we have tryed to avoid SSL and password for the mail server, so we have added in **values.yaml** following:

```
# REANA components configuration
components:
  reana_server:
    environment:
      REANA_EMAIL_SMTP_SERVER: "XXX.XXX.XX.XXX"
      REANA_EMAIL_SMTP_PORT: 25
      REANA_EMAIL_SENDER: "test@aip.de" 
      REANA_EMAIL_RECEIVER: "noreply@aip.de"
      REANA_EMAIL_LOGIN: ""
      REANA_EMAIL_PASSWORD: ""

      FLASK_ENV: "development"
```
Looks like our mail server getting requests but email is rejected by following error:
```
postfix/smtp[21505]: XXXXXXX: to=<XXXX@XXXX>, relay=127.0.0.1[127.0.0.1]:10024, delay=0.07, delays=0.01/0.01/0/0.06, dsn=2.6.0, status=sent (250 2.6.0 Ok, discarded, id=14729-02 - BAD HEADER)
``` 

Any idea how to fix this?
Would be great that REANA can use directly mail server without SSL if no password is set and the mailserver port is 25

thank you beforehand,
Arman.
