### ISSUE TITLE
reana.yaml: load parameters from an external file

### ISSUE THREAD

**Issue by mdonadoni** [reanahub/reana#699]
Parameters of a workflow are specified in the `inputs.parameters` section of `reana.yaml`, like this:

```yaml
inputs:
  parameters:
    myparam1: myvalue1
    myparam2: myvalue2
```

However, in case of a CWL or Snakemake workflow, it is also possible to load parameters from an external file by providing a special `input` parameter ([source code](https://github.com/reanahub/reana-commons/blob/f766dd46ecc1a5777e1c8c4dfeb358bec25926ab/reana_commons/specification.py#L97-L104))

```yaml
inputs:
  parameters:
    input: my-parameters.yaml
```

We should introduce a new property in `reana.yaml` to support loading parameters from a file also for serial or Yadage workflows. One possible name for this property can be `parameter_file`:

```yaml
inputs:
  parameter_file: my-parameters.yaml
```

If we want to support multiple parameter files at the same time, then we should use `parameter_files`:

```yaml
inputs:
  parameter_files:
    - my-parameters-first-stage.yaml
    - my-parameters-second-stage.yaml
```

In this second case, we also need to decide how to handle parameters defined in different files but having the same name.
