### ISSUE TITLE
Deploying 0.9 on Rancher 2.71: Cannot create DB 

### ISSUE THREAD

**Issue by arm2arm** [reanahub/reana#706]
I am trying to deploy the reana0.9 as a heml app in the rancher 2.71 with Kubernetes Version: v1.24.10

The steps are following:
1)  install apps with  charts nfs-subdir-external-provisioner:4.0.18 used for 3x PV classes 
* nfs-default(unused from reana)
*  reanahub-infrastructure-volume-storage-class
*  reanahub-shared-volume-storage-class
2) using 	https://reanahub.github.io/reana chart
* changing storage prameters:
````
infrastructure_storage:
  access_modes: ReadWriteMany
  backend: nfs
  volume_size: 10
shared_storage:
  access_modes: ReadWriteMany
  backend: nfs
  volume_size: 200
````
I can see the two PVCs are bounded with RWX flags 

Deployment goes smoothly for all services ony *reanahub-db* is failing with:
```
chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
```
how to fix this issue?
Thank you beforehand,
