### ISSUE TITLE
ci: introduce `yamllint` checks

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#836]
It would be useful to enrich our CI check suite in order to validate YAML files.

We are using YAML in Helm charts, in REANA demo examples, but also in all the repositories with respect to commitlint.

In our deployment repository (using GitLab), we do:

(1) In GitLab CI:

```yaml
lint-yamllint:
  image: registry.gitlab.com/pipeline-components/yamllint:latest
  script:
    - ./run-tests.sh --check-yamllint
```

(2) In `run-tests.sh`:

```bash
...

check_yamllint () {
    yamllint .
}

check_all () {
    check_black
    check_flake8
    check_pydocstyle
    check_shellcheck
    check_yamllint
}

for arg in "$@"
do
    case $arg in
        --check-black) check_black;;
        --check-flake8) check_flake8;;
        --check-pydocstyle) check_pydocstyle;;
        --check-shellcheck) check_shellcheck;;
        --check-yamllint) check_yamllint;;
        *) echo "invalid argument $arg" && exit 2;;
    esac
done
```

(3) We have the following `.yamllint.yaml` configuration file so that starting "---" is optional:

```yaml
extends: default

rules:
  document-start: disable
  line-length: disable
```

The goal of this issue is to introduce `yamllint` in a similar way to all our GitHub repositories. This will consist of:

- enriching `run-tests.sh` so that the checking would work locally;
- finding out an appropriate GitHub action and enriching `.github/workflows/ci.yml` so that the checking would be always executed during pull request time.
