### ISSUE TITLE
release: publishing docker images is not triggered automatically

### ISSUE THREAD

**Issue by mdonadoni** [reanahub/reana#856]
GitHub CI is configured to automatically build and publish docker images of cluster components when a new tag is pushed, see for example reana-server ([source](https://github.com/reanahub/reana-server/blob/999d71667827dc420ab57ef3c2cca8417622fa65/.github/workflows/ci.yml#L183-L188)):

```yaml
  release-docker:
    runs-on: ubuntu-24.04
    if: >
      vars.RELEASE_DOCKER == 'true' &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/')
```

However, it seems like this is not triggered by the tag created by release-please. At the moment, the workaround is to delete the tag and to recreate it.

We should modify the CI so that a new release by release-please also triggers automatically the publishing of docker images, for example by exploiting the output values of the GitHub action like [`release_created` ](https://github.com/googleapis/release-please-action?tab=readme-ov-file#outputs)
