### ISSUE TITLE
Regarding Configuring storage volumes

### ISSUE THREAD

**Issue by XaverStiensmeier** [reanahub/reana#892]
I am new to Kubernetes so if you feel like these questions are out of the scope of REANA, feel free to let me know and I will try to find answers elsewhere.

After your response to my last issue, I tried to setup the nfs in the way REANA expects it: https://github.com/reanahub/reana/issues/879

For that I followed https://docs.reana.io/administration/configuration/configuring-storage-volumes/ and created an nfs-share at /var/reana on the master `192.168.33.24`. I verified that the workers are able to access that share. I then tried to set everything up in Kubernetes by following your tutorial and additional tutorials I found online.

# Process

## NFS-Server Provisioner

I tried `helm install reana-dev-storage stable/nfs-server-provisioner -f nfs-provisioner-values.yaml` but got an error that stable is not available. So I looked it up and did

```
helm repo add nfs-ganesha-server-and-external-provisioner https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
helm install my-release nfs-ganesha-server-and-external-provisioner/nfs-server-provisioner -f nfs-provisioner-values.yaml
```

with

```
# nfs provisioner; defining the class
storageClass:
  defaultClass: true
  name: reana-shared-volume-storage-class
```

## PV

Then I set up the persistant volume with `kubectl apply -f nfs-pv.yaml` and

```yaml
# nfs-pv; to create the volume within kubernetes
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi  # Replace with the desired size
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/reana  # Path as exported from the NFS server
    server: 192.168.33.24  # nfs-server ip
```

Executed after everything:

```sh
kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                    STORAGECLASS                        VOLUMEATTRIBUTESCLASS   REASON   AGE
nfs-pv                                     10Gi       RWX            Retain           Available                                                                                <unset>                          21m
pvc-7a5c15b3-df78-4dac-9d0e-0372da62c0cb   10Gi       RWX            Delete           Bound       default/nfs-pvc                          reana-shared-volume-storage-class   <unset>                          20m
pvc-99e44255-016e-4936-a753-9cd19253062e   20G        RWX            Delete           Bound       default/reana-shared-persistent-volume   reana-shared-volume-storage-class   <unset>                          19m
```

## PVC

Then I set up the persistant volume claim with `kubectl apply -f nfs-pvc.yaml` and

```yaml
# nfs-pvc; to claim the volume for the pod
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "reana-shared-volume-storage-class" # hardcoded class name as requested in the issue
```

Executed after everything:

```sh
kubectl get pvc
NAME                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                        VOLUMEATTRIBUTESCLASS   AGE
nfs-pvc                          Bound    pvc-7a5c15b3-df78-4dac-9d0e-0372da62c0cb   10Gi       RWX            reana-shared-volume-storage-class   <unset>                 21m
reana-shared-persistent-volume   Bound    pvc-99e44255-016e-4936-a753-9cd19253062e   20G        RWX            reana-shared-volume-storage-class   <unset>                 20m
```

The `get` results make me think whether I accidentally added two of each.

## REANA

I then tried to install REANA with `helm install reana reanahub/reana -f myvalues.yaml --wait` and

```yaml
# myvalues.yaml 
node_label_infrastructure: reana.io/system=infrastructure
node_label_infrastructuredb: reana.io/system=infrastructuredb
node_label_infrastructuremq: reana.io/system=infrastructuremq
node_label_runtimebatch: reana.io/system=runtimebatch
node_label_runtimejobs: reana.io/system=runtimejobs
node_label_runtimesessions: reana.io/system=runtimesessions

shared_storage:
  backend: nfs
  volume_size: 20  # Adjust size based on expected data requirements
  access_modes: ReadWriteMany
  nfs:
    server: 192.168.33.24
    path: /var/reana
```

but I got:
```sh
helm install reana reanahub/reana -f myvalues.yaml --wait
W0423 11:54:50.967341  324783 warnings.go:70] annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
Error: INSTALLATION FAILED: context deadline exceeded
```

I then tried to gather as much info as possible, but I have a hard time to identify what exactly causes the issue. The logs of the three pods that are stuck in `ContainerCreating` reveal connection issues and mounting issues for the pvc.

```sh
kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
reana-cache-777764c45f-szjn6                 1/1     Running             0          22m
reana-db-cccb69675-l6mcd                     1/1     Running             0          22m
reana-dev-storage-nfs-server-provisioner-0   1/1     Running             0          41m
reana-message-broker-0                       0/1     ContainerCreating   0          22m
reana-server-5959cff87c-qpjsw                0/2     ContainerCreating   0          22m
reana-traefik-5b6cc878f9-lhgxm               1/1     Running             0          22m
reana-ui-7c5ffb5c79-wrgmf                    1/1     Running             0          22m
reana-workflow-controller-f97795874-ml8m8    0/2     ContainerCreating   0          22m
```

```sh
helm status reana
NAME: reana
LAST DEPLOYED: Wed Apr 23 12:09:56 2025
NAMESPACE: default
STATUS: failed
REVISION: 1
TEST SUITE: None
NOTES:
The REANA system has been installed!

If you are upgrading from a previous REANA release series, you may need to
upgrade database schema now:

   $ kubectl -n default exec -i -t deployment/reana-server -c rest-api -- reana-db alembic upgrade

Please see the dedicated upgrade documentation at
<https://docs.reana.io/administration/deployment/upgrading-db/>

If you are deploying REANA for the first time, there are a few steps left to
finalise its configuration.

1. Initialise the database:

    $ kubectl -n default exec deployment/reana-server -c rest-api -- \
        ./scripts/create-database.sh

2. Create administrator user and corresponding access token:

    $ mytoken=$(kubectl -n default exec deployment/reana-server -c rest-api -- \
          flask reana-admin create-admin-user --email john.doe@example.org \
                                              --password mysecretpassword)

3. Store administrator access token as Kubernetes secret:

    $ kubectl -n default create secret generic reana-admin-access-token \
        --from-literal=ADMIN_ACCESS_TOKEN="$mytoken"

4. Try to run your first REANA example:

    $ firefox https://localhost:30443

   Or, using command line:

    $ # install REANA client
    $ pip install --user reana-client
    $ # set environment variables for REANA client
    $ export REANA_SERVER_URL=https://localhost:30443
    $ export REANA_ACCESS_TOKEN="$mytoken"
    $ # test connection to the REANA cluster
    $ reana-client ping
    $ # clone and run a simple analysis example
    $ git clone https://github.com/reanahub/reana-demo-root6-roofit
    $ cd reana-demo-root6-roofit
    $ reana-client run -w demo

Thanks for flying REANA 🚀
```

```sh
kubectl describe pod reana-message-broker-0 -n default
Name:             reana-message-broker-0
Namespace:        default
Priority:         0
Service Account:  default
Node:             k8s-worker-1/192.168.33.222
Start Time:       Wed, 23 Apr 2025 12:09:58 +0000
Labels:           app=reana-message-broker
                  apps.kubernetes.io/pod-index=0
                  controller-revision-hash=reana-message-broker-9b4c84d79
                  statefulset.kubernetes.io/pod-name=reana-message-broker-0
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    StatefulSet/reana-message-broker
Containers:
  message-broker:
    Container ID:  
    Image:         docker.io/reanahub/reana-message-broker:0.9.3
    Image ID:      
    Ports:         5672/TCP, 15672/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /start.sh
      $(RABBIT_MQ_USER)
      $(RABBIT_MQ_PASS)
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      RABBIT_MQ_USER:  <set to the key 'user' in secret 'reana-message-broker-secrets'>      Optional: false
      RABBIT_MQ_PASS:  <set to the key 'password' in secret 'reana-message-broker-secrets'>  Optional: false
    Mounts:
      /var/lib/rabbitmq/mnesia from reana-infrastructure-volume (rw,path="rabbitmq/mnesia")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-s5j9q (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   False 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  reana-infrastructure-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  reana-shared-persistent-volume
    ReadOnly:   false
  kube-api-access-s5j9q:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              reana.io/system=infrastructuremq
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    26m                 default-scheduler  Successfully assigned default/reana-message-broker-0 to k8s-worker-1
  Warning  FailedMount  35s (x10 over 24m)  kubelet            MountVolume.SetUp failed for volume "pvc-99e44255-016e-4936-a753-9cd19253062e" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o retrans=2,timeo=30,vers=3 10.104.1.78:/export/pvc-99e44255-016e-4936-a753-9cd19253062e /var/lib/kubelet/pods/cd1be44c-265d-4f5d-b8c9-79adf0dfdded/volumes/kubernetes.io~nfs/pvc-99e44255-016e-4936-a753-9cd19253062e
Output: mount.nfs: Connection timed out for 10.104.1.78:/export/pvc-99e44255-016e-4936-a753-9cd19253062e on /var/lib/kubelet/pods/cd1be44c-265d-4f5d-b8c9-79adf0dfdded/volumes/kubernetes.io~nfs/pvc-99e44255-016e-4936-a753-9cd19253062e
```

```sh
kubectl logs reana-server-5959cff87c-qpjsw -n default
Defaulted container "rest-api" out of: rest-api, scheduler
Error from server (BadRequest): container "rest-api" in pod "reana-server-5959cff87c-qpjsw" is waiting to start: ContainerCreating
```

```sh
kubectl logs reana-workflow-controller-f97795874-ml8m8 -n default
Defaulted container "rest-api" out of: rest-api, job-status-consumer
Error from server (BadRequest): container "rest-api" in pod "reana-workflow-controller-f97795874-ml8m8" is waiting to start: ContainerCreating
```
